---
apiVersion: v1
kind: Namespace
metadata:
  name: argo
  labels:
    app.kubernetes.io/part-of: k8s-event-triage
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
  labels:
    app.kubernetes.io/part-of: k8s-event-triage
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: k8s-event-triage
